import GetStarted from "../features/Authentication/components/register/GetStarted";
import styles from '../features/Authentication/assets/styles/Auth.module.css';
import { AuthProvider } from "../features/Authentication/context/Authcontext";
import Head from "next/head";

export default function CreateShop({types}){
    return(
        <AuthProvider>
            <Head>
                <title>Localbly|Createshop</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.createshop}>
                <div className={styles.innerSection}>
                    <div className={styles.registerFormImg}><img src="/logo.png" /></div>
                    <GetStarted/>
                </div>
            </div>
        </AuthProvider>
    );
}