import LoginForm from "../features/Authentication/components/form/LoginForm";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
import styles from '../features/Authentication/assets/styles/Auth.module.css';
import { useDisclosure } from '@mantine/hooks';
import MediumModal from "../components/Reusable/Modal";
import { Button } from "@mantine/core";
import ChangePassword from "../features/Profile/components/ui/ChangePassword";
export default function Login(){
    const [opened, { open, close }] = useDisclosure(false);
        return(
            <>
            <Head>
                <title>Localbly|Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           <div className={styles.loginPage}>
                <div className={styles.loginImg}>
                    <Image src="/logo.png" alt="site logo" fill />
                </div>
                <div className={styles.loginForm}>
                    <div className={styles.loginFormTitle}>
                        <h3>Welcome Back!</h3>
                        <p>Login to your shop</p>
                    </div>
                    <LoginForm />
                    <Button type="button" variant="subtle" mt="lg" mb="lg" onClick={open}>Forgot password?</Button>
                    <div className="or">
                        <span className="divider"></span>
                        <div className="or-content"><h3>OR</h3></div>
                        <span className="divider"></span>
                    </div>
                    <Link href="/register" className="alt-btn">Create Account</Link>
                </div>
                
           </div>
           <MediumModal opened={opened} close={close} text="Change Password">
                <ChangePassword />
          </MediumModal>         
                    
                    
                        
                
            </>
        );
     
    
}

