import { useState } from 'react';
import Head from 'next/head'
import { useSession } from "next-auth/react";
import {AppShell, Navbar,Header, LoadingOverlay, Text,Avatar,MediaQuery,Burger, Menu,NavLink,useMantineTheme,ActionIcon, useMantineColorScheme} from '@mantine/core';
import Image from 'next/image';
import Link from 'next/link';
import { signOut } from 'next-auth/react';
import PageBreadcrumbs from "./Breadcrumb";
import NavLinks from "./NavLinks";
export default function Layout({children}){
    const [opened, setOpened] = useState(false);
    const { data:session, status } = useSession();
    if(status == 'loading' || !session){return <LoadingOverlay visible={session} overlayBlur={4} />}
    let nameParts = session?.user.name.split(" ");
    let firstLetter = nameParts[0]?.charAt(0).toUpperCase();
    let secondLetter = nameParts[1]?.charAt(0).toUpperCase();
    let initials = firstLetter + secondLetter;

    return(
        <>
            <Head>
                <title>Localbly</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AppShell
                navbarOffsetBreakpoint="md"
                asideOffsetBreakpoint="sm"
                navbar={
                    <Navbar p="md" hiddenBreakpoint="sm" hidden={!opened} width={{ sm: 260, lg: 300 }} className='navbar'>
                        <NavLinks />
                    </Navbar>
                }
               
                header={
                    <Header height={{ base: 50, md: 60 }} p="md">
                    <div style={{ display: 'flex', alignItems: 'center', height: '100%', justifyContent: 'space-between' }} className='header'>
                        <MediaQuery largerThan="sm" styles={{ display: 'none' }}>
                        <Burger
                            opened={opened}
                            onClick={() => setOpened((o) => !o)}
                            size="sm"
                            mr="xl"
                        />
                        </MediaQuery>
                        <div className='site-logo'><Image src="/logo.png" priority="true"  fill alt="localbly logo"/></div>
                        <div className='nav-options'>
                            <Menu withArrow>
                            <Menu.Target><Avatar color="cyan" radius="xl">{initials}</Avatar></Menu.Target>
                            <Menu.Dropdown>
                                <NavLink icon={<i class="ri-login-circle-line"></i>} onClick={signOut} component={Link} href="/" label="Log-out" />
                                <NavLink icon={<i class="ri-user-3-line"></i>} component={Link} href="/account" label="Profile" />
                            </Menu.Dropdown>
                            </Menu>
                            <div className="user">
                            <Text fz="md">{session?.user.name}</Text>
                            </div>
                        </div>
                    </div>
                </Header>
                }
            >
                <main className='main-content'>
                    <PageBreadcrumbs />
                    {children}
                </main>
            </AppShell>
        </>
    );
}